/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as RemindersRouteImport } from './routes/reminders'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as GamesIndexRouteImport } from './routes/games/index'
import { Route as GamesMemoryRouteImport } from './routes/games/memory'
import { Route as GamesSequenceRouteImport } from './routes/games/sequence'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindersRoute = RemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesMemoryRoute = GamesMemoryRouteImport.update({
  id: '/games/memory',
  path: '/games/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesSequenceRoute = GamesSequenceRouteImport.update({
  id: '/games/sequence',
  path: '/games/sequence',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/progress': typeof ProgressRoute
  '/reminders': typeof RemindersRoute
  '/signup': typeof SignupRoute
  '/games/memory': typeof GamesMemoryRoute
  '/games/sequence': typeof GamesSequenceRoute
  '/games/': typeof GamesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/progress': typeof ProgressRoute
  '/reminders': typeof RemindersRoute
  '/signup': typeof SignupRoute
  '/games/memory': typeof GamesMemoryRoute
  '/games/sequence': typeof GamesSequenceRoute
  '/games': typeof GamesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/progress': typeof ProgressRoute
  '/reminders': typeof RemindersRoute
  '/signup': typeof SignupRoute
  '/games/memory': typeof GamesMemoryRoute
  '/games/sequence': typeof GamesSequenceRoute
  '/games/': typeof GamesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/progress'
    | '/reminders'
    | '/signup'
    | '/games/memory'
    | '/games/sequence'
    | '/games/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/progress'
    | '/reminders'
    | '/signup'
    | '/games/memory'
    | '/games/sequence'
    | '/games'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/progress'
    | '/reminders'
    | '/signup'
    | '/games/memory'
    | '/games/sequence'
    | '/games/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ProgressRoute: typeof ProgressRoute
  RemindersRoute: typeof RemindersRoute
  SignupRoute: typeof SignupRoute
  GamesMemoryRoute: typeof GamesMemoryRoute
  GamesSequenceRoute: typeof GamesSequenceRoute
  GamesIndexRoute: typeof GamesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminders': {
      id: '/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof RemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/memory': {
      id: '/games/memory'
      path: '/games/memory'
      fullPath: '/games/memory'
      preLoaderRoute: typeof GamesMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/sequence': {
      id: '/games/sequence'
      path: '/games/sequence'
      fullPath: '/games/sequence'
      preLoaderRoute: typeof GamesSequenceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ProgressRoute: ProgressRoute,
  RemindersRoute: RemindersRoute,
  SignupRoute: SignupRoute,
  GamesMemoryRoute: GamesMemoryRoute,
  GamesSequenceRoute: GamesSequenceRoute,
  GamesIndexRoute: GamesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
