/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as RemindersRouteImport } from './routes/reminders'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as CaregiverIndexRouteImport } from './routes/caregiver/index'
import { Route as CaregiverProfileRouteImport } from './routes/caregiver/profile'
import { Route as GamesIndexRouteImport } from './routes/games/index'
import { Route as GamesMemoryRouteImport } from './routes/games/memory'
import { Route as GamesSequenceRouteImport } from './routes/games/sequence'
import { Route as JournalIndexRouteImport } from './routes/journal/index'
import { Route as JournalIdRouteImport } from './routes/journal/$id'
import { Route as JournalNewRouteImport } from './routes/journal/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindersRoute = RemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const CaregiverIndexRoute = CaregiverIndexRouteImport.update({
  id: '/caregiver/',
  path: '/caregiver/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaregiverProfileRoute = CaregiverProfileRouteImport.update({
  id: '/caregiver/profile',
  path: '/caregiver/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesMemoryRoute = GamesMemoryRouteImport.update({
  id: '/games/memory',
  path: '/games/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesSequenceRoute = GamesSequenceRouteImport.update({
  id: '/games/sequence',
  path: '/games/sequence',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalIdRoute = JournalIdRouteImport.update({
  id: '/journal/$id',
  path: '/journal/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalNewRoute = JournalNewRouteImport.update({
  id: '/journal/new',
  path: '/journal/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/reminders': typeof RemindersRoute
  '/signup': typeof SignupRoute
  '/caregiver/profile': typeof CaregiverProfileRoute
  '/games/memory': typeof GamesMemoryRoute
  '/games/sequence': typeof GamesSequenceRoute
  '/journal/$id': typeof JournalIdRoute
  '/journal/new': typeof JournalNewRoute
  '/caregiver/': typeof CaregiverIndexRoute
  '/games/': typeof GamesIndexRoute
  '/journal/': typeof JournalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/reminders': typeof RemindersRoute
  '/signup': typeof SignupRoute
  '/caregiver/profile': typeof CaregiverProfileRoute
  '/games/memory': typeof GamesMemoryRoute
  '/games/sequence': typeof GamesSequenceRoute
  '/journal/$id': typeof JournalIdRoute
  '/journal/new': typeof JournalNewRoute
  '/caregiver': typeof CaregiverIndexRoute
  '/games': typeof GamesIndexRoute
  '/journal': typeof JournalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/reminders': typeof RemindersRoute
  '/signup': typeof SignupRoute
  '/caregiver/profile': typeof CaregiverProfileRoute
  '/games/memory': typeof GamesMemoryRoute
  '/games/sequence': typeof GamesSequenceRoute
  '/journal/$id': typeof JournalIdRoute
  '/journal/new': typeof JournalNewRoute
  '/caregiver/': typeof CaregiverIndexRoute
  '/games/': typeof GamesIndexRoute
  '/journal/': typeof JournalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/profile'
    | '/progress'
    | '/reminders'
    | '/signup'
    | '/caregiver/profile'
    | '/games/memory'
    | '/games/sequence'
    | '/journal/$id'
    | '/journal/new'
    | '/caregiver/'
    | '/games/'
    | '/journal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/profile'
    | '/progress'
    | '/reminders'
    | '/signup'
    | '/caregiver/profile'
    | '/games/memory'
    | '/games/sequence'
    | '/journal/$id'
    | '/journal/new'
    | '/caregiver'
    | '/games'
    | '/journal'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/profile'
    | '/progress'
    | '/reminders'
    | '/signup'
    | '/caregiver/profile'
    | '/games/memory'
    | '/games/sequence'
    | '/journal/$id'
    | '/journal/new'
    | '/caregiver/'
    | '/games/'
    | '/journal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
  RemindersRoute: typeof RemindersRoute
  SignupRoute: typeof SignupRoute
  CaregiverProfileRoute: typeof CaregiverProfileRoute
  GamesMemoryRoute: typeof GamesMemoryRoute
  GamesSequenceRoute: typeof GamesSequenceRoute
  JournalIdRoute: typeof JournalIdRoute
  JournalNewRoute: typeof JournalNewRoute
  CaregiverIndexRoute: typeof CaregiverIndexRoute
  GamesIndexRoute: typeof GamesIndexRoute
  JournalIndexRoute: typeof JournalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminders': {
      id: '/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof RemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caregiver/': {
      id: '/caregiver/'
      path: '/caregiver'
      fullPath: '/caregiver/'
      preLoaderRoute: typeof CaregiverIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caregiver/profile': {
      id: '/caregiver/profile'
      path: '/caregiver/profile'
      fullPath: '/caregiver/profile'
      preLoaderRoute: typeof CaregiverProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/memory': {
      id: '/games/memory'
      path: '/games/memory'
      fullPath: '/games/memory'
      preLoaderRoute: typeof GamesMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/sequence': {
      id: '/games/sequence'
      path: '/games/sequence'
      fullPath: '/games/sequence'
      preLoaderRoute: typeof GamesSequenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/': {
      id: '/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$id': {
      id: '/journal/$id'
      path: '/journal/$id'
      fullPath: '/journal/$id'
      preLoaderRoute: typeof JournalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/new': {
      id: '/journal/new'
      path: '/journal/new'
      fullPath: '/journal/new'
      preLoaderRoute: typeof JournalNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ProfileRoute: ProfileRoute,
  ProgressRoute: ProgressRoute,
  RemindersRoute: RemindersRoute,
  SignupRoute: SignupRoute,
  CaregiverProfileRoute: CaregiverProfileRoute,
  GamesMemoryRoute: GamesMemoryRoute,
  GamesSequenceRoute: GamesSequenceRoute,
  JournalIdRoute: JournalIdRoute,
  JournalNewRoute: JournalNewRoute,
  CaregiverIndexRoute: CaregiverIndexRoute,
  GamesIndexRoute: GamesIndexRoute,
  JournalIndexRoute: JournalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
